### ISSUE TITLE
Failing to run simulation mode.

### ISSUE THREAD

**Issue by xinuo** [apache/incubator-teaclave#300]
I had built Teaclave in simulation mode
`
docker run --rm -v $(pwd):/teaclave -w /teaclave   -it teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1:latest    bash -c ". /root/.cargo/env && \
     mkdir -p build && cd build && \
     . /opt/sgxsdk/environment && \
     cmake -DTEST_MODE=ON -DSGX_SIM_MODE=ON .. && \
     make   --trace"
`

I want to launch all services after building Teaclave.

But when i run this code 
`
 (cd docker && docker-compose -f docker-compose-ubuntu-1804.yml up --build)
`
and it show
`
ERROR: for 1d54dc72d75f_teaclave-storage-service  Cannot start service teaclave-storage-service: linux runtime spec devices: error gathering device information while adding custom device "/dev/isgx": no such file or director
`

So,why the simulation mode is not work.May be i do wrong step?

My os : Ubuntu 18.04.4 LTS
My CPU:Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
There is no sgx tech in the CPU.

**Comment by mssun** [comment]
Under simulation mode, you also need to change the `docker-compose-ubuntu-1804.yml` file accordingly to remove unused device/volume mappings.

That is, comment out these lines:

```
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - /dev/isgx
```
