### ISSUE TITLE
Missing schema in "teaclave_xxx_service" advertised address

### ISSUE THREAD

**Issue by hiroki-chen** [apache/incubator-teaclave#706]
The configuration file `runtime.config.toml` in `docker` folder seems to be improperly written because I found the following key value pairs

```toml
[internal_endpoints]
authentication = { listen_address = "0.0.0.0:17776", advertised_address = "teaclave-authentication-service:17776" }
management     = { listen_address = "0.0.0.0:17777", advertised_address = "teaclave-management-service:17777" }
storage        = { listen_address = "0.0.0.0:17778", advertised_address = "teaclave-storage-service:17778" }
access_control = { listen_address = "0.0.0.0:17779", advertised_address = "teaclave-access-control-service:17779" }
execution      = { listen_address = "0.0.0.0:17770", advertised_address = "teaclave-execution-service:17770" }
scheduler      = { listen_address = "0.0.0.0:17780", advertised_address = "teaclave-scheduler-service:17780" }
```

would trigger errors when I tried to run the Teaclave service with docker-compose. Sample error:

```sh
teaclave-execution-service         | [ERROR teaclave_execution_service_enclave::ecall] Failed to run service: Missing schema in "teaclave_scheduler_service" advertised address
```

It could be fixed by adding the prefix `https://`, i.e., it should be `advertised_address = "https://teaclave-authentication-service:17776"`. For your information, I built Teaclave in simulation mode.

Thank you for your attention, and I can create a PR if you need it :)

BTW, the docker runtime config file does not match that under `config` directory.
